name: SpawnJoin
main: me.NUKMUK.SpawnJoin
version: 1.3.3
author: NUKMUK
website: https://github.com/NUKMUK/SpawnJoin

commands:
  sj:
    usage: "/sj <set|get|spawn|reload> [x] [y] [z] [yaw]"
    aliases: [sjoin, spawnjoin]

permissions:
  spawnjoin.help:
    default: op
  spawnjoin.set:
    default: op
  spawnjoin.get:
    default: op
  spawnjoin.spawn:
    default: op
  spawnjoin.reload:
    default: op